
# Site settings
title: Meow
email: kenaser12345@gmail.com
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://banacat.tk/" # the base hostname & protocol for your site

markdown: kramdown
# toc_levels: 1……2

# paginate: 10
# paginate_path: ":num"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - blog pull and debug.bat
